language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="brew update && brew install pixman freetype harfbuzz"
    - os: linux
      addons:
        apt:
          packages:
            - libpixman-1-dev libfreetype6-dev libharfbuzz-dev libx11-dev libxcursor-dev
      env:
        - XVFB=xvfb-run
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9 libpixman-1-dev libfreetype6-dev libharfbuzz-dev libx11-dev libxcursor-dev
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
        - XVFB=xvfb-run
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5 libpixman-1-dev libfreetype6-dev libharfbuzz-dev libx11-dev libxcursor-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - XVFB=xvfb-run
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6 libpixman-1-dev libfreetype6-dev libharfbuzz-dev libx11-dev libxcursor-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - XVFB=xvfb-run
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7 libpixman-1-dev libfreetype6-dev libharfbuzz-dev libx11-dev libxcursor-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - XVFB=xvfb-run

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - $XVFB ctest --output-on-failure
